export const  REDIRECT_URL = window.location.origin + window.location.pathname;
export const WAYL_API_KEY = "WWI2LZxl51giAqxffsl4Dw==:8wTmnJpGrBt8vrpeAmqerVpmWplcYXp58fIanNs1Iv7c7dPBgyR/Pz5pp4Oh99F9RrwDHRQmzEjCVYAoNVuWE0oDrmPXGXbhsJM0C97ooJiHWiyhhS01146entAjMOqHchxkBJxjfOuFJCLwlEwd1VycObwtDrw9nNWJ38nHero=";
